### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by byron-hawkins** [Maratyszcza/confu#2]
When I run the `setup.py` script, I get the following error:

    Traceback (most recent call last):
      File "./setup.py", line 3, in <module>
        from confu import __version__, __maintainer__, __email__
      File "/home/sureau/lab/shaker/benchmarks/confu/confu/__init__.py", line 35, in <module>
        from confu.platform import Platform
      File "/home/sureau/lab/shaker/benchmarks/confu/confu/platform.py", line 230, in <module>
        host = Platform(detect_host())
      File "/home/sureau/lab/shaker/benchmarks/confu/confu/platform.py", line 198, in detect_host
        import platform
      File "/home/sureau/lab/python/confu/platform.py", line 230, in <module>
        host = Platform(detect_host())
      File "/home/sureau/lab/python/confu/platform.py", line 199, in detect_host
        machine = platform.machine()
    AttributeError: 'module' object has no attribute 'machine'

The same things happens if I try to run the configuration script for NNPACK.

    > python --version
    Python 2.7.13

**Comment by Maratyszcza** [comment]
`platform` module is built-in in Python, and must have `machine()` function. If it doesn't something is wrong with your Python distribution.
