### ISSUE TITLE
Issue with Confu.Standard_parser

### ISSUE THREAD

**Issue by brystreus** [Maratyszcza/confu#4]
I've been attempting to run the confu module and I've been recieving errors about confu.standard_parser not being an attribute within confu, which it isn't. I'm currently attempting to setup a program that utilizes confu.standard_parser and I'm stuck

**Comment by Maratyszcza** [comment]
Did you install confu from this repo or from pip? The `pip` version is a different project

**Comment by brystreus** [comment]
I downloaded via pip. Do you have link to the repo version of confu.

**Comment by Maratyszcza** [comment]
@Brystreus: repo is the link. Use `[sudo] pip install --upgrade git+https://github.com/Maratyszcza/confu` to install confu from the repo

**Comment by brystreus** [comment]
Thanks, I'll try this out right now.

**Comment by brystreus** [comment]
I used this method and still recieved the same error, I also used the zip file and recieved the same error. Do you have a source code file that I can just copy for confu ?

**Comment by Maratyszcza** [comment]
This repo is the source code. Most likely, you have several versions of confu and/or Python interpreters in the system. Maybe uninstall all confu packages and then install again?

**Comment by vladkovalev** [comment]
Hi, I've tried to install confu package , you provided and got the following error (on Windows 10 64bit):
CRITICAL:root:failed to detect the host platform: sys.platform = win32, platform.machine = AMD64

Please, suggest how to solve it
Thanks in advance,
Vlad

**Comment by Manamama** [comment]
Even after 4 years I need to reopen it. 
```
~/downloads/pthreadpool $ ls
 bench         cmake_install.cmake   CMakeLists.txt.save   examples         googlebenchmark            googletest-download   lib        󱧼 src
 bin           CMakeCache.txt        configure.py          FXdiv            googlebenchmark-download   googletest-source     LICENSE     test
 BUILD.bazel   CMakeFiles            confu.yaml            FXdiv-download   googlebenchmark-source     include               Makefile    WORKSPACE
 cmake         CMakeLists.txt        CTestTestfile.cmake   FXdiv-source     googletest                 jni                   README.md  
~/downloads/pthreadpool $ python configure.py 
Detected root directory: /data/data/com.termux/files/home/downloads/pthreadpool
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/pthreadpool/configure.py", line 38, in <module>
    main(sys.argv[1:]).generate()
    ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/downloads/pthreadpool/configure.py", line 10, in main
    build = confu.Build.from_options(options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/confu/builds/base.py", line 55, in from_options
    return UnixBuild(root_dir, options.target, options.toolchain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/confu/builds/unix.py", line 11, in __init__
    super(UnixBuild, self).__init__(root_dir, target)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/confu/builds/base.py", line 23, in __init__
    self.manifest = Project.from_root(root_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/confu/manifest.py", line 36, in from_root
    manifest_yaml = yaml.load(manifest_text)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load() missing 1 required posit


```


Termux, all new, this box:
```
Environment at user system (use it to compare, troubleshoot, etc):

Operating System:
- Name: Android 11 aarch64, Linux, 4.14.186+ (Termux)
- Kernel: 4.14.186+
- Shell: /data/data/com.termux/files/usr/bin/bashso 
uname -a
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android                
(Termux)
                                           
                      

Compiler:
- GCC Version: gcc-10/tur-packages, now 10.5.0 aarch64 [installed]
- g++ (symbolic link to clang-18), clang version 18.1.5
Target: aarch64-unknown-linux-android24         
Thread model: posix                             
InstalledDir: /data/data/com.termux/files/usr/bin
- Make version:                                   
GNU Make 4.4.1                                  
Built for aarch64-unknown-linux-android  
- Abseil C++ library: 20240116.2 for the AArch64


Python Environment:
- Python Version: 3.11.6
- pip Version: 24.0
- Cython Version: 3.0.10
- setuptools Version: 69.5.1
- PyTorch Version: 2.0.1 *
- numpy Version: 1.17.0 *


Environment Variables:
PREFIX is: /data/data/com.termux/files/usr
PATH: /data/data/com.termux/files/home/.sdkman/candidates/java/current/bin:/data/data/com.termux/files/home/perl5/bin:/data/data/com.termux/files/usr/bin:/system/bin/:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/home/.local/bin                                                                                         
LD_LIBRARY_PATH:     {empty}                                                                           
CFLAGS:           {empty}                                                                              
LDFLAGS: -lpython3.11 -llog                                                                     
CPPFLAGS: {empty}
LD_LIBRARY_PATH: {empty}
LD_LIBRARY_PATH:  {empty}                                                                           
CFLAGS:      {empty}                                                                                   
LDFLAGS: -lpython3.11 -llog                                                                     
CPPFLAGS: {empty}
C_INCLUDE_PATH : {empty}                                
CPLUS_INCLUDE_PATH:    {empty}                        
CPLUS_INCLUDE_PATH: {empty}
```
